# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d238c3095cecd7d66f7c087f642035cd"
name = "MyPosExtension"
handle = "myposextension"
application_url = "https://ta-room-cnet-needed.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_inventory,write_inventory,read_locations,read_markets_home"

[auth]
redirect_urls = ["https://ta-room-cnet-needed.trycloudflare.com/auth/callback", "https://ta-room-cnet-needed.trycloudflare.com/auth/shopify/callback", "https://ta-room-cnet-needed.trycloudflare.com/api/auth/callback"]

[pos]
embedded = true
